name: Update Library References
run-name: update library refs
on:
  push:
    branches:
      - lib

jobs:
  update-hash:
    name: Update hash
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout lib branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Establish Library Reference
        shell: pwsh
        run: | 
          git fetch origin main
          git worktree add ../main origin/main
          Set-Location ../main
          $CommitHash = (git rev-parse HEAD)
          Get-Item "./f95/*", "./lc/*" | ForEach-Object -Process {(Get-Content $_) -replace '[a-f0-9]{40}', $CommitHash | Set-Content $_}
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git add -A
          git commit -m "Fix library references"
          git push --force origin HEAD:main